version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-barcos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: barcos_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red-barcos

  app:
    build: .
    container_name: spring-barcos
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/barcos_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - red-barcos

volumes:
  mysql_data:

networks:
  red-barcos:
